{"name": "密码为空", "status": "broken", "statusDetails": {"message": "AttributeError: 'CaseData' object has no attribute 'casea_data'", "trace": "self = <autotest03.testcases.test_my_interface01.test_login.TestLogin object at 0x04113238>\ncase = <comms.excel_utils.CaseData object at 0x04021298>\n\n    @allure.severity(\"critical\")  # 设置用例优先级\n    @pytest.mark.parametrize(\"case\", cases)\n    def test_login(self, case):  # 所有的测试方法必须以test开头\n        allure.dynamic.title(case.case_title)  # 动态获取用例名称,allure报告显示用例名称\n        allure.attach(body=case.url, name='接口路径')\n>       allure.attach(body=case.casea_data, name='请求参数')\nE       AttributeError: 'CaseData' object has no attribute 'casea_data'\n\ntest_login.py:30: AttributeError"}, "attachments": [{"name": "接口路径", "source": "b98624d0-5344-4697-9b3b-6b4ba73ba461-attachment.attach"}], "parameters": [{"name": "case", "value": "<comms.excel_utils.CaseData object at 0x04021298>"}], "start": 1646039094957, "stop": 1646039094957, "uuid": "853bf0c4-25cd-4cbb-83f4-98a99d3d0888", "historyId": "0a5850f360156f3c5d6052f500c596eb", "testCaseId": "b62a022e3184708d2d40012e446c9b1d", "fullName": "test_login.TestLogin#test_login", "labels": [{"name": "feature", "value": "登录接口测试"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-V37VTV5"}, {"name": "thread", "value": "65284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}